name: Hello World!

on:
  push:
  pull_request:

jobs:
  linux:
    runs-on: ubuntu-latest
    name: Linux
    steps:
      - uses: actions/checkout@v3
      - name: Compile
        run: make hello.c
      - name: Run
        run: ./hello.o

  macos:
    runs-on: macos-latest
    name: Macos
    steps:
      - uses: actions/checkout@v3
      - name: Compile
        run: gcc hello.c
      - name: Run
        run: ./hello.o
