name: Hello World!

on:
  push:
  pull_request:

jobs:
  ubuntu:
    runs-on: windows-latest
    name: Windows
    steps:
      - uses: actions/checkout@v3
      - name: compile
        run: gcc hello.c
